- name: test my new module
  hosts: localhost
  gather_facts: true
  tasks:
  - name: get lscpu facts
    alainchiasson.inhouse.lscpu_facts:
  - name: Dump
    debug:
      msg: "{{ hostvars[inventory_hostname].lscpu }}"
